### ISSUE TITLE
System.NullReferenceException when calling SvgImageSource.Create()

### ISSUE THREAD

**Issue by idan-rubin** [softlion/XamSvg-Samples#1]
Adding the following code to XamSvg.XamFormsDemo\XamSvg.Demo\Pages\MainPage.xaml.cs class, in line 60 causes a NullReferenceException:
var imageSource = SvgImageSource.Create("res:images.refresh");

**Comment by softlion** [comment]
Fixed / see UserVoice

**Comment by idan-rubin** [comment]
Thanks.

**Comment by xperseguers** [comment]
Looks like I have a similar problem, where is this "UserVoice" information?

**Comment by softlion** [comment]
Your issue is not the same. In your stack trace there is no xamsvg crash. Check your code again, or use a SvgImage instead.

**Comment by xperseguers** [comment]
When I return a ImageSource.FromFile instead, I get no exception.

Xavier Perseguers
Sent from my iPhone

On 25 Apr 2017, at 22:02, Softlion (Benjamin Mayrargue) <notifications@github.com<mailto:notifications@github.com>> wrote:


Your issue is not the same. In your stack trace there is no xamsvg crash. Check your code again, or use a SvgImage instead.

-

**Comment by softlion** [comment]
Fixed in 2.3.4.3
Caused by a late use of the resulting ImageSource, disposing the memory stream used.
